export const data = {
  users: [
    {
      ID: 1,
      profilePhoto: "John.jpg",
      description: "Business Owner",
      name: "John Doe",
      email: "John@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 2,
      profilePhoto: "Jane1.jpg",
      description: "Freelance web developer",
      name: "Jane Doe",
      email: "Jane@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 3,
      profilePhoto: "User-img.jpg",
      description: "Front-End Developer",
      name: "Soroush Shariaty",
      email: "Soroush@gmail.com",
      password: "123456",
      isAdmin: true,
    },
    {
      ID: 4,
      profilePhoto: "Elena.jpg",
      description: "Nurse",
      name: "Elena Smith",
      email: "Elena@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 5,
      profilePhoto: "William.jpg",
      description: "Assistant Professor",
      name: "William Moore",
      email: "William@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 6,
      profilePhoto: "James.jpg",
      description: "Petroleum Engineer",
      name: "James McCarthy",
      email: "James@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 7,
      profilePhoto: "Sara.jpg",
      description: "Psychologist",
      name: "Sara Wembley",
      email: "Sara@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 8,
      profilePhoto: "Madison.jpg",
      description: "Teacher",
      name: "Madison Merchant",
      email: "Madison@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 9,
      profilePhoto: "Antonio.jpg",
      description: "Accountant",
      name: "Antonio Rodriguez",
      email: "Antonio@gmail.com",
      password: "123456",
      isAdmin: false,
    },
    {
      ID: 10,
      profilePhoto: "Lisa.jpg",
      description: "Secretary",
      name: "Lisa West",
      email: "Lisa@gmail.com",
      password: "123456",
      isAdmin: false,
    },
  ],
  posts: [
    {
      postId: 1,
      postOwnerID: 1,
      // postPhoto: "../../../public/images/post-pic.jpg",

      postPhoto: {
        name: "post2.jpg",
        width: 800,
        height: 600,
      },
      description: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
      vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
       causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
      Time: "...",
      likeCount: 11,
      Comments: [
        {
          commentId: 11,
          commentOwnerID: 5,
          text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                 vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                  causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
          replies: [
            {
              commentId: 111,
              commentOwnerID: 2,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 1111,
                  commentOwnerID: 1,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 1112,
                  commentOwnerID: 3,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
            {
              commentId: 12,
              commentOwnerID: 7,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 121,
                  commentOwnerID: 9,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 122,
                  commentOwnerID: 3,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      postId: 2,
      postOwnerID: 4,
      // postPhoto: "../../../public/images/post1.jpg",

      postPhoto: {
        name: "post1.jpg",
        width: 750,
        height: 350,
      },
      description: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
      vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
       causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
      Time: "...",
      likeCount: 43,
      Comments: [
        {
          commentId: 21,
          commentOwnerID: 6,
          text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                 vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                  causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
          replies: [
            {
              commentId: 211,
              commentOwnerID: 8,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 2111,
                  commentOwnerID: 5,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 2112,
                  commentOwnerID: 2,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
            {
              commentId: 212,
              commentOwnerID: 2,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 2121,
                  commentOwnerID: 6,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 2122,
                  commentOwnerID: 3,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      postId: 3,
      postOwnerID: 3,
      // postPhoto: "../../../public/images/post2.jpg",
      postPhoto: {
        name: "post2.jpg",
        width: 800,
        height: 600,
      },
      description: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
      vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
       causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
      Time: "...",
      likeCount: 121,
      Comments: [
        {
          commentId: 31,
          commentOwnerID: 1,
          text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                 vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                  causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
          replies: [
            {
              commentId: 311,
              commentOwnerID: 4,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 3111,
                  commentOwnerID: 6,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 3112,
                  commentOwnerID: 1,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
            {
              commentId: 312,
              commentOwnerID: 2,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 3121,
                  commentOwnerID: 3,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 3122,
                  commentOwnerID: 1,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      postId: 4,
      postOwnerID: 6,
      // postPhoto: "../../../public/images/post-pic.jpg",
      postPhoto: {
        name: "post3.jpg",
        width: 600,
        height: 400,
      },
      description: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
      vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
       causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
      Time: "...",
      likeCount: 4,
      Comments: [
        {
          commentId: 41,
          commentOwnerID: 2,
          text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                 vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                  causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
          replies: [
            {
              commentId: 411,
              commentOwnerID: 3,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 4111,
                  commentOwnerID: 2,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 4112,
                  commentOwnerID: 7,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
            {
              commentId: 412,
              commentOwnerID: 4,
              text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                        vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                         causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
              replies: [
                {
                  commentId: 4121,
                  commentOwnerID: 9,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
                {
                  commentId: 4122,
                  commentOwnerID: 3,
                  text: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
                                vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
                                 causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      postId: 5,
      postOwnerID: 3,
      postPhoto: {
        name: "post1.jpg",
        width: 750,
        height: 350,
      },
      description: `Lorem ipsum dolor sit amet, et minim liber patrioque mel,
      vis latine alienum cu, ex pri summo vivendum similique. Offendit delicata ne has,
       causae temporibus est ei. Id usu brute scaevola, sit ei regione tacimates.`,
      Time: "...",
      likeCount: 1100,
      Comments: [],
    },
  ],
};
